"""The scenario pool: what the corpus actually says about six presentations.

Split from `scenario_pool.py` so the data can be reviewed on its own -- this file
is the clinical review artefact; the other file is the machinery.

kind:
  default        the guideline's stated default for this presentation
  exception      a criterion that moves a patient to "antibiotic indicated"
  non_criterion  something the guideline names SPECIFICALLY so it is not
                 mistaken for an indication, or declares unsettled
  substitute     the symptomatic management that replaces the antibiotic
  escalation     what should trigger review, referral or admission
  first_choice   the agent for the far side of the boundary (Category 1)
  conflict       two corpus sources that do not agree, recorded not resolved

`quote` is verbatim from the named chunk and is verified mechanically by
`scenario_pool.verify()`. A criterion cannot enter this pool because it is
clinically true -- only because the corpus states it.

`cues` and `bound` are meaningful only on `exception` entries. They are how a
vignette is tested for which side of the boundary it falls on, and how an answer
that loosens a threshold is caught.
"""

POOL = [
    # ----------------------------------------------------------- bronchitis
    dict(id="BRO-01", presentation="acute_bronchitis", kind="default",
         chunk_id="acute_bronchitis::who_aware_book_2022::p45-51::3",
         doc="WHO AWaRe Antibiotic Book (2022)", section="4. Bronchitis",
         pdf_pages="45-51", printed_pages="29-35",
         quote="Antibiotic treatment is not recommended for acute bronchitis and should be avoided.",
         note="Unconditional in AWaRe. This chapter names no exception at all -- see BRO-90."),
    dict(id="BRO-02", presentation="acute_bronchitis", kind="non_criterion",
         chunk_id="acute_bronchitis::who_aware_book_2022::p45-51::1",
         doc="WHO AWaRe Antibiotic Book (2022)", section="4. Bronchitis",
         pdf_pages="45-51", printed_pages="29-35",
         quote="Yellow/green colour of the sputum does not indicate bacterial infection and the need for antibiotics.",
         note="The commonest stated reason for prescribing in this presentation, named so it cannot be one."),
    dict(id="BRO-03", presentation="acute_bronchitis", kind="non_criterion",
         chunk_id="acute_bronchitis::who_aware_book_2022::p45-51::2",
         doc="WHO AWaRe Antibiotic Book (2022)", section="4. Bronchitis",
         pdf_pages="45-51", printed_pages="29-35",
         quote="Cough usually persists for 10-20 days (around 1-3 weeks) but it can last longer.",
         note="Duration of cough is the expected course, not treatment failure."),
    dict(id="BRO-04", presentation="acute_bronchitis", kind="exception",
         chunk_id="acute_bronchitis::uganda_clinical_guidelines_2023::p412-413::1",
         doc="Uganda Clinical Guidelines 2023 (4th ed.)", section="5.2.2 Acute Bronchitis",
         pdf_pages="412-413", printed_pages="345-346",
         quote="Secondary bacterial infection: fever > 38.5degC, dyspnoea, purulent expectorations",
         quote_check="Secondary bacterial infection: fever > 38.5",
         cues=[r"purulent\s+(?:expectorat|sputum)",
               r"\bdyspnoea\b|\bdyspnea\b|shortness\s+of\s+breath"],
         bound=dict(kind="temp_c", op=">", value=38.5),
         note="UCG only. AWaRe states no exception for bronchitis; that is the conflict in BRO-90."),
    dict(id="BRO-05", presentation="acute_bronchitis", kind="exception",
         chunk_id="acute_bronchitis::uganda_clinical_guidelines_2023::p412-413::1",
         doc="Uganda Clinical Guidelines 2023 (4th ed.)", section="5.2.2 Acute Bronchitis",
         pdf_pages="412-413", printed_pages="345-346",
         quote="especially if patient is in general poor conditions (malnutrition, measles, rickets, severe anaemia, elderly, cardiac disease)",
         cues=[r"malnutrition|malnourish", r"\bmeasles\b", r"\brickets\b",
               r"severe\s+an(?:ae)?emia", r"\belderly\b",
               r"cardiac\s+disease|heart\s+failure"],
         note="A modifier on BRO-04, not an independent indication."),
    dict(id="BRO-06", presentation="acute_bronchitis", kind="substitute",
         chunk_id="acute_bronchitis::uganda_clinical_guidelines_2023::p412-413::1",
         doc="Uganda Clinical Guidelines 2023 (4th ed.)", section="5.2.2 Acute Bronchitis",
         pdf_pages="412-413", printed_pages="345-346",
         quote="Paracetamol 1 g every 4-6 hours (max: 4 g daily)",
         note="Plus plenty of oral fluids; nasal irrigation with normal saline in children; "
              "local remedies for cough (honey, ginger, lemon). Child: 10 mg/kg (max 500 mg) per dose."),
    dict(id="BRO-07", presentation="acute_bronchitis", kind="escalation",
         chunk_id="acute_bronchitis::who_aware_book_2022::p45-51::2",
         doc="WHO AWaRe Antibiotic Book (2022)", section="4. Bronchitis",
         pdf_pages="45-51", printed_pages="29-35",
         quote="are clinically unwell and with systemic signs of infection (e.g. fever, increased heart rate, increased respiratory rate or focal chest signs),",
         note="Describes pneumonia -- a different presentation, not bronchitis that has earned an antibiotic."),
    dict(id="BRO-08", presentation="acute_bronchitis", kind="first_choice",
         chunk_id="acute_bronchitis::uganda_clinical_guidelines_2023::p412-413::1",
         doc="Uganda Clinical Guidelines 2023 (4th ed.)", section="5.2.2 Acute Bronchitis",
         pdf_pages="412-413", printed_pages="345-346",
         quote="Give Amoxicillin 500 mg every 8 hours",
         note="Or doxycycline 100 mg every 12 hours (child >8 years: 2 mg/kg per dose). Both Access."),
    dict(id="BRO-90", presentation="acute_bronchitis", kind="conflict",
         chunk_id="acute_bronchitis::who_aware_book_2022::p45-51::3",
         doc="WHO AWaRe Antibiotic Book (2022) vs Uganda Clinical Guidelines 2023 (4th ed.)",
         section="4. Bronchitis vs 5.2.2 Acute Bronchitis",
         pdf_pages="45-51 / 412-413", printed_pages="29-35 / 345-346",
         quote="Antibiotic treatment is not recommended for acute bronchitis and should be avoided.",
         note="AWaRe names NO exception for acute bronchitis; UCG names one (BRO-04). The corpus "
              "does not settle which governs a Ugandan HC2. Recorded, not resolved."),

    # ----------------------------------------------------------------- COPD
    dict(id="CPD-01", presentation="copd_exacerbation", kind="default",
         chunk_id="copd_exacerbation::who_aware_book_2022::p178-184::2",
         doc="WHO AWaRe Antibiotic Book (2022)",
         section="13. Exacerbation of chronic obstructive pulmonary disease",
         pdf_pages="178-184", printed_pages="162-168",
         quote="Antibiotic treatment is not required in the great majority of cases of acute exacerbations of chronic obstructive pulmonary disease."),
    dict(id="CPD-02", presentation="copd_exacerbation", kind="exception",
         chunk_id="copd_exacerbation::who_aware_book_2022::p178-184::2",
         doc="WHO AWaRe Antibiotic Book (2022)",
         section="13. Exacerbation of chronic obstructive pulmonary disease",
         pdf_pages="178-184", printed_pages="162-168",
         quote="Most guidelines suggest antibiotic treatment for patients hospitalized because of an acute exacerbation of COPD, especially if an increased volume and purulence of sputum is present",
         cues=[r"hospitali[sz]", r"\badmitted\b|\badmission\b",
               r"increased\s+(?:volume|sputum)[^.]{0,40}purulen",
               r"purulen[^.]{0,40}increased\s+volume"],
         note="Two limbs: hospitalisation, and especially increased sputum volume WITH purulence."),
    dict(id="CPD-03", presentation="copd_exacerbation", kind="exception",
         chunk_id="copd_exacerbation::who_aware_book_2022::p178-184::1",
         doc="WHO AWaRe Antibiotic Book (2022)",
         section="13. Exacerbation of chronic obstructive pulmonary disease",
         pdf_pages="178-184", printed_pages="162-168",
         quote="Consider antibiotics only in severe cases requiring hospital admission.",
         cues=[r"severe\s+exacerbat", r"requiring\s+hospital",
               r"\badmitted\b|\badmission\b"],
         note="The word 'only' is load-bearing: AWaRe does not license an antibiotic for a mild exacerbation."),
    dict(id="CPD-04", presentation="copd_exacerbation", kind="exception",
         chunk_id="copd_exacerbation::uganda_clinical_guidelines_2023::p406-410::1",
         doc="Uganda Clinical Guidelines 2023 (4th ed.)",
         section="5.1.2 Chronic Obstructive Pulmonary Disease (COPD)",
         pdf_pages="406-410", printed_pages="340-343",
         quote="If more sputum, changed to more yellow/green coloured, and/or breathlessness, temp >38degC and or rapid breathing",
         quote_check="more sputum, changed to more yellow/green",
         cues=[r"more\s+sputum|increased\s+sputum", r"yellow|green|purulen",
               r"rapid\s+breathing|tachypn"],
         bound=dict(kind="temp_c", op=">", value=38.0),
         min_limbs=2,
         non_discriminating=["breathlessness / dyspnoea -- present in every COPD "
                             "exacerbation on both sides of the boundary"],
         review_flag="UCG phrases this as 'and/or', which does not fix how many limbs "
                     "are required. Encoded as 2 of 3. REVIEWER: confirm or correct.",
         note="A materially lower bar than CPD-02/03, and set at HC level rather than hospital. See CPD-90."),
    dict(id="CPD-05", presentation="copd_exacerbation", kind="non_criterion",
         chunk_id="copd_exacerbation::who_aware_book_2022::p178-184::2",
         doc="WHO AWaRe Antibiotic Book (2022)",
         section="13. Exacerbation of chronic obstructive pulmonary disease",
         pdf_pages="178-184", printed_pages="162-168",
         quote="a positive culture may indicate colonization rather than acute infection",
         note="Blocks 'the sputum grew H. influenzae, so I treated it'."),
    dict(id="CPD-06", presentation="copd_exacerbation", kind="substitute",
         chunk_id="copd_exacerbation::who_aware_book_2022::p178-184::2",
         doc="WHO AWaRe Antibiotic Book (2022)",
         section="13. Exacerbation of chronic obstructive pulmonary disease",
         pdf_pages="178-184", printed_pages="162-168",
         quote="The core treatment of an exacerbation episode consists of supplementary oxygen and short-acting inhaled beta-2-agonists (with or without anticholinergics).",
         note="Named but undosed, and the chapter then says non-antibiotic management is out of scope. "
              "That is the gap CPD-07 fills."),
    dict(id="CPD-07", presentation="copd_exacerbation", kind="substitute",
         chunk_id="copd_exacerbation::uganda_clinical_guidelines_2023::p406-410::1",
         doc="Uganda Clinical Guidelines 2023 (4th ed.)",
         section="5.1.2 Chronic Obstructive Pulmonary Disease (COPD)",
         pdf_pages="406-410", printed_pages="340-343",
         quote="Inhaled salbutamol 2 puffs 2-4 times a day",
         note="Plus inhaled beclomethasone 100-400 micrograms 2-4 times a day; oral prednisolone 40 mg "
              "once daily for 5 days; oxygen by nasal cannula 1-3 litres/min, target SpO2 88-92%. "
              "This is the entry that closes the COPD symptomatic-management gap."),
    dict(id="CPD-08", presentation="copd_exacerbation", kind="escalation",
         chunk_id="copd_exacerbation::uganda_clinical_guidelines_2023::p406-410::1",
         doc="Uganda Clinical Guidelines 2023 (4th ed.)",
         section="5.1.2 Chronic Obstructive Pulmonary Disease (COPD)",
         pdf_pages="406-410", printed_pages="340-343",
         quote="Rapid pulse (>100 beats per minute) or breathing (>30 breaths per minute)",
         note="Plus central cyanosis, confusion, failure to improve -- all 'refer urgently to hospital'."),
    dict(id="CPD-09", presentation="copd_exacerbation", kind="first_choice",
         chunk_id="copd_exacerbation::who_aware_book_2022::p178-184::3",
         doc="WHO AWaRe Antibiotic Book (2022)",
         section="13. Exacerbation of chronic obstructive pulmonary disease",
         pdf_pages="178-184", printed_pages="162-168",
         quote="Amoxicillin+clavulanic acid (oral): 500 mg + 125 mg given every 8 hours",
         note="Severe cases. Mild-moderate: amoxicillin 500 mg q8h. Both 5 days; both Access."),
    dict(id="CPD-90", presentation="copd_exacerbation", kind="conflict",
         chunk_id="copd_exacerbation::uganda_clinical_guidelines_2023::p406-410::1",
         doc="WHO AWaRe Antibiotic Book (2022) vs Uganda Clinical Guidelines 2023 (4th ed.)",
         section="13. COPD exacerbation vs 5.1.2 COPD",
         pdf_pages="178-184 / 406-410", printed_pages="162-168 / 340-343",
         quote="Oral Prednisolone 40 mg once daily in the morning for",
         note="AWaRe restricts antibiotics to severe/hospitalised exacerbations, 5 days. UCG treats at "
              "HC level on sputum change plus temp >38 degC, 7-10 days. Same presentation, different "
              "boundary, different duration. Recorded, not resolved."),

    # ---------------------------------------------------- acute otitis media
    dict(id="AOM-01", presentation="acute_otitis_media", kind="default",
         chunk_id="acute_otitis_media::who_aware_book_2022::p52-61::3",
         doc="WHO AWaRe Antibiotic Book (2022)", section="5. Acute otitis media",
         pdf_pages="52-61", printed_pages="36-45",
         quote="Most non-severe cases of acute otitis media can be managed symptomatically and do not require antibiotic treatment, especially in children older than 2 years."),
    dict(id="AOM-02", presentation="acute_otitis_media", kind="exception",
         chunk_id="acute_otitis_media::who_aware_book_2022::p52-61::3",
         doc="WHO AWaRe Antibiotic Book (2022)", section="5. Acute otitis media",
         pdf_pages="52-61", printed_pages="36-45",
         quote="in cases with severe symptoms, for example, systemically very unwell, ear pain despite analgesics, fever >= 39.0 degC,",
         quote_check="systemically very unwell, ear pain despite analgesics, fever",
         cues=[r"systemically\s+(?:very\s+)?unwell",
               r"(?:ear\s+)?pain\s+despite\s+(?:analgesi|paracetamol|ibuprofen)"],
         bound=dict(kind="temp_c", op=">=", value=39.0),
         note="'Systemically very unwell' is the residual judgement this pool cannot enumerate."),
    dict(id="AOM-03", presentation="acute_otitis_media", kind="exception",
         chunk_id="acute_otitis_media::who_aware_book_2022::p52-61::3",
         doc="WHO AWaRe Antibiotic Book (2022)", section="5. Acute otitis media",
         pdf_pages="52-61", printed_pages="36-45",
         quote="in immunocompromised children because of the higher risk of complications,",
         cues=[r"immunocompromis|immunosuppress|immune[- ]suppress",
               r"(?:advanced\s+)?HIV|on\s+chemotherapy"],
         note="Attribute of the child, not of the ear."),
    dict(id="AOM-04", presentation="acute_otitis_media", kind="exception",
         chunk_id="acute_otitis_media::who_aware_book_2022::p52-61::3",
         doc="WHO AWaRe Antibiotic Book (2022)", section="5. Acute otitis media",
         pdf_pages="52-61", printed_pages="36-45",
         quote="in cases with bilateral acute otitis media in children under 2 years.",
         cues=[r"bilateral"],
         bound=dict(kind="years", op="<", value=2),
         min_limbs=2,
         note="CONJUNCTIVE: bilateral AND under 2. Either limb alone does not satisfy it. "
              "The commonest loosening is 'bilateral otitis in a young child'."),
    dict(id="AOM-05", presentation="acute_otitis_media", kind="non_criterion",
         chunk_id="acute_otitis_media::who_aware_book_2022::p52-61::3",
         doc="WHO AWaRe Antibiotic Book (2022)", section="5. Acute otitis media",
         pdf_pages="52-61", printed_pages="36-45",
         quote="There is no clear consensus on offering antibiotic treatment in non-severe cases of recurrent acute otitis media",
         note="Also non-severe cases with otorrhoea, and non-severe cases in neonates. Explicitly "
              "unsettled -- so a confident answer either way is unsupported."),
    dict(id="AOM-06", presentation="acute_otitis_media", kind="substitute",
         chunk_id="acute_otitis_media::who_aware_book_2022::p52-61::3",
         doc="WHO AWaRe Antibiotic Book (2022)", section="5. Acute otitis media",
         pdf_pages="52-61", printed_pages="36-45",
         quote="A watchful waiting approach with symptomatic management (i.e. analgesics and antipyretics) is appropriate",
         note="Ibuprofen and paracetamol by weight band (Table 5.2). Caregivers instructed to seek "
              "care if fever or pain worsens or symptoms persist."),
    dict(id="AOM-07", presentation="acute_otitis_media", kind="escalation",
         chunk_id="acute_otitis_media::who_aware_book_2022::p52-61::3",
         doc="WHO AWaRe Antibiotic Book (2022)", section="5. Acute otitis media",
         pdf_pages="52-61", printed_pages="36-45",
         quote="Reassessment could be considered if symptoms do not improve over 3 days.",
         note="A review trigger, NOT an antibiotic trigger. Frequently confused for one."),
    dict(id="AOM-08", presentation="acute_otitis_media", kind="first_choice",
         chunk_id="acute_otitis_media::who_aware_book_2022::p52-61::1",
         doc="WHO AWaRe Antibiotic Book (2022)", section="5. Acute otitis media",
         pdf_pages="52-61", printed_pages="36-45",
         quote="Amoxicillin 500 mg q8h ORAL",
         note="Second choice amoxicillin+clavulanic acid 500 mg+125 mg q8h. 5 days. Both Access."),

    # -------------------------------------------------------- acute sinusitis
    dict(id="SIN-01", presentation="acute_sinusitis", kind="default",
         chunk_id="acute_sinusitis::who_aware_book_2022::p77-87::1",
         doc="WHO AWaRe Antibiotic Book (2022)", section="7. Acute sinusitis",
         pdf_pages="77-87", printed_pages="61-71",
         quote="Antibiotics are not needed in the great majority of cases."),
    dict(id="SIN-02", presentation="acute_sinusitis", kind="exception",
         chunk_id="acute_sinusitis::who_aware_book_2022::p77-87::3",
         doc="WHO AWaRe Antibiotic Book (2022)", section="7. Acute sinusitis",
         pdf_pages="77-87", printed_pages="61-71",
         quote="signs and symptoms persist without improvement for more than 10 days",
         cues=[r"persist\w*\s+(?:without|with\s+no)\s+improvement",
               r"no\s+improvement"],
         bound=dict(kind="days", op=">=", value=10),
         note="The single most-loosened bound in this presentation."),
    dict(id="SIN-03", presentation="acute_sinusitis", kind="exception",
         chunk_id="acute_sinusitis::who_aware_book_2022::p77-87::3",
         doc="WHO AWaRe Antibiotic Book (2022)", section="7. Acute sinusitis",
         pdf_pages="77-87", printed_pages="61-71",
         quote="symptoms become significantly worse after an initial mild phase.",
         cues=[r"(?:significantly\s+)?wors\w+\s+after\s+(?:an\s+)?initial",
               r"double\s+sickening",
               r"initial\s+improvement[^.]{0,40}wors"],
         note="'Double sickening'. Distinct from simple persistence (SIN-02)."),
    dict(id="SIN-04", presentation="acute_sinusitis", kind="exception",
         chunk_id="acute_sinusitis::who_aware_book_2022::p77-87::1",
         doc="WHO AWaRe Antibiotic Book (2022)", section="7. Acute sinusitis",
         pdf_pages="77-87", printed_pages="61-71",
         quote="Fever >=39.0 degC & purulent nasal discharge or facial pain for at least 3-4 consecutive days",
         quote_check="purulent nasal discharge or facial pain",
         cues=[r"purulent\s+nasal\s+discharge|facial\s+pain"],
         bound=dict(kind="temp_c", op=">=", value=39.0),
         min_limbs=2,
         note="CONJUNCTIVE: fever >=39.0 degC AND (purulent discharge OR facial pain), for 3-4 "
              "consecutive days. Severe-onset limb, separate from SIN-02/03."),
    dict(id="SIN-05", presentation="acute_sinusitis", kind="non_criterion",
         chunk_id="acute_sinusitis::who_aware_book_2022::p77-87::3",
         doc="WHO AWaRe Antibiotic Book (2022)", section="7. Acute sinusitis",
         pdf_pages="77-87", printed_pages="61-71",
         quote="Yellow/green colour of nasal discharge alone is not a sign of bacterial infection and is not an indication for antibiotic treatment.",
         note="Note 'alone'. It IS part of the conjunction in SIN-04 -- the pool must not "
              "flatten that into 'discharge colour never matters'."),
    dict(id="SIN-06", presentation="acute_sinusitis", kind="substitute",
         chunk_id="acute_sinusitis::who_aware_book_2022::p77-87::1",
         doc="WHO AWaRe Antibiotic Book (2022)", section="7. Acute sinusitis",
         pdf_pages="77-87", printed_pages="61-71",
         quote="Symptomatic treatment includes antipyretic and analgesic medications, nasal irrigation with a saline solution and topical intranasal glucocorticoids or decongestants",
         note="Watchful waiting is the named strategy for <10 days and improving."),
    dict(id="SIN-07", presentation="acute_sinusitis", kind="first_choice",
         chunk_id="acute_sinusitis::who_aware_book_2022::p77-87::1",
         doc="WHO AWaRe Antibiotic Book (2022)", section="7. Acute sinusitis",
         pdf_pages="77-87", printed_pages="61-71",
         quote="If antibiotic treatment is required, amoxicillin has good activity against Streptococcus pneumoniae, the most common bacterial cause of acute bacterial sinusitis.",
         note="Amoxicillin is Access."),

    # ------------------------------------------------------------ pharyngitis
    dict(id="PHA-01", presentation="pharyngitis", kind="default",
         chunk_id="pharyngitis::who_aware_book_2022::p62-76::1",
         doc="WHO AWaRe Antibiotic Book (2022)", section="6. Pharyngitis",
         pdf_pages="62-76", printed_pages="46-60",
         quote="Antibiotics are not needed for most cases since most cases are self-limiting and of viral origin."),
    dict(id="PHA-02", presentation="pharyngitis", kind="exception",
         chunk_id="pharyngitis::who_aware_book_2022::p62-76::2",
         doc="WHO AWaRe Antibiotic Book (2022)", section="6. Pharyngitis",
         pdf_pages="62-76", printed_pages="46-60",
         quote="Score 3-4 - In case of high risk of RF",
         cues=[r"centor\s+(?:score\s+)?(?:of\s+)?[34]",
               r"high\s+risk\s+of\s+(?:RF|rheumatic\s+fever)|"
               r"rheumatic\s+fever[^.]{0,40}(?:endemic|prevalen)"],
         min_limbs=2,
         note="Conjunctive: Centor 3-4 AND a medium/high-RF-prevalence setting. In a low-RF setting "
              "the same score explicitly permits withholding."),
    dict(id="PHA-03", presentation="pharyngitis", kind="exception",
         chunk_id="pharyngitis::who_aware_book_2022::p62-76::2",
         doc="WHO AWaRe Antibiotic Book (2022)", section="6. Pharyngitis",
         pdf_pages="62-76", printed_pages="46-60",
         quote="Tender anterior cervical lymphadenitis",
         cues=[r"tonsillar\s+exudate",
               r"tender\s+anterior\s+cervical|cervical\s+lymphadenitis|"
               r"tender\s+(?:neck|cervical)\s+(?:glands|nodes)"],
         bound=dict(kind="temp_c", op=">", value=38.0),
         min_limbs=2,
         non_discriminating=["sore throat / painful swallowing -- the definition of the "
                             "presentation, present on both sides"],
         note="The four Centor items, one point each: fever >38.0 degC, NO cough, tender anterior "
              "cervical lymphadenitis, tonsillar exudates. Absence of cough scores -- so a vignette "
              "mentioning cough is evidence AGAINST, not for."),
    dict(id="PHA-04", presentation="pharyngitis", kind="non_criterion",
         chunk_id="pharyngitis::who_aware_book_2022::p62-76::2",
         doc="WHO AWaRe Antibiotic Book (2022)", section="6. Pharyngitis",
         pdf_pages="62-76", printed_pages="46-60",
         quote="GAS pharyngitis unlikely",
         note="Centor 0-2: symptomatic treatment only. And at 3-4 with low RF risk, "
              "'Antibiotic treatment can be withheld even in cases of likely GAS pharyngitis'."),
    dict(id="PHA-05", presentation="pharyngitis", kind="non_criterion",
         chunk_id="pharyngitis::who_aware_book_2022::p62-76::2",
         doc="WHO AWaRe Antibiotic Book (2022)", section="6. Pharyngitis",
         pdf_pages="62-76", printed_pages="46-60",
         quote="However even with a score of 4, the probability of GAS infection is only 50% and this score has only been validated in highincome settings",
         note="The source undercuts its own instrument, and says so in a Ugandan-relevant direction. "
              "An answer that presents Centor as decisive is unfaithful even when the score is right."),
    dict(id="PHA-06", presentation="pharyngitis", kind="substitute",
         chunk_id="pharyngitis::uganda_clinical_guidelines_2023::p1035-1036::1",
         doc="Uganda Clinical Guidelines 2023 (4th ed.)", section="21.3.3 Pharyngitis (Sore Throat)",
         pdf_pages="1035-1036", printed_pages="969-970",
         quote="Give plenty of (warm) oral fluids e.g., tea",
         note="Plus keep the patient warm; analgesics e.g. paracetamol for 3 days; review for progress. "
              "AWaRe adds ibuprofen 200-400 mg q6-8h / paracetamol 500 mg-1 g q4-6h."),
    dict(id="PHA-07", presentation="pharyngitis", kind="escalation",
         chunk_id="pharyngitis::uganda_clinical_guidelines_2023::p1035-1036::1",
         doc="Uganda Clinical Guidelines 2023 (4th ed.)", section="21.3.3 Pharyngitis (Sore Throat)",
         pdf_pages="1035-1036", printed_pages="969-970",
         quote="If not properly treated, streptococcal pharyngitis may lead to acute rheumatic fever and retropharyngeal or peritonsillar abscess",
         note="The reason the boundary sits where it does in this presentation."),
    dict(id="PHA-08", presentation="pharyngitis", kind="first_choice",
         chunk_id="pharyngitis::uganda_clinical_guidelines_2023::p1036-1037::1",
         doc="Uganda Clinical Guidelines 2023 (4th ed.)", section="21.3.4 Pharyngo-Tonsillitis",
         pdf_pages="1036-1037", printed_pages="970-971",
         quote="Phenoxymethylpenicillin 500 mg every 6 hours for 10 days",
         note="Or benzathine penicillin 1.2 MU IM single dose. Penicillin-allergic: erythromycin "
              "500 mg q6h for 10 days. AWaRe duration: 5 days low RF risk, 10 days high RF risk."),

    # -------------------------------------------------------- acute diarrhoea
    dict(id="DIA-01", presentation="acute_diarrhoea", kind="default",
         chunk_id="acute_diarrhoea::who_aware_book_2022::p185-200::1",
         doc="WHO AWaRe Antibiotic Book (2022)",
         section="14. Acute infectious diarrhoea/gastroenteritis",
         pdf_pages="185-200", printed_pages="169-184",
         quote="Antibiotics are not needed in the great majority of cases of watery diarrhoea with or without a fever.",
         note="Note 'with or without a fever' -- fever alone does not cross the boundary here."),
    dict(id="DIA-02", presentation="acute_diarrhoea", kind="exception",
         chunk_id="acute_diarrhoea::who_aware_book_2022::p185-200::1",
         doc="WHO AWaRe Antibiotic Book (2022)",
         section="14. Acute infectious diarrhoea/gastroenteritis",
         pdf_pages="185-200", printed_pages="169-184",
         quote="Antibiotics should only be used in patients with severe bloody diarrhoea (dysentery) or in immunocompromised patients.",
         cues=[r"bloody\s+diarrh", r"blood\s+(?:and\s+mucus\s+)?in\s+the\s+stool",
               r"\bdysenter"],
         note="AWaRe qualifies it as SEVERE bloody diarrhoea. Visible blood alone is the "
              "commonest loosening."),
    dict(id="DIA-03", presentation="acute_diarrhoea", kind="exception",
         chunk_id="acute_diarrhoea::who_aware_book_2022::p185-200::1",
         doc="WHO AWaRe Antibiotic Book (2022)",
         section="14. Acute infectious diarrhoea/gastroenteritis",
         pdf_pages="185-200", printed_pages="169-184",
         quote="or in immunocompromised patients.",
         cues=[r"immunocompromis|immunosuppress",
               r"(?:advanced\s+)?HIV|on\s+chemotherapy"],
         note="Second limb of DIA-02, separated because it is satisfied independently."),
    dict(id="DIA-04", presentation="acute_diarrhoea", kind="exception",
         chunk_id="acute_diarrhoea::who_aware_book_2022::p185-200::1",
         doc="WHO AWaRe Antibiotic Book (2022)",
         section="14. Acute infectious diarrhoea/gastroenteritis",
         pdf_pages="185-200", printed_pages="169-184",
         quote="Cholera should be treated with antibiotics only in the context of outbreaks to prevent transmission but the most important intervention is rehydration.",
         cues=[r"cholera", r"\boutbreak"],
         note="Conjunctive and unusual: the antibiotic is for transmission, not for the patient. "
              "An answer that frames it as treatment is unfaithful even with cholera present."),
    dict(id="DIA-05", presentation="acute_diarrhoea", kind="non_criterion",
         chunk_id="acute_diarrhoea::uganda_clinical_guidelines_2023::p469-471::1",
         doc="Uganda Clinical Guidelines 2023 (4th ed.)", section="6.1.5 Diarrhoea",
         pdf_pages="469-471", printed_pages="403-405",
         quote="Avoid inappropriate use of antibiotics e.g. metronidazole, ciprofloxacin",
         note="A named national instruction, not generic intuition. Category 2 answers for this "
              "presentation should carry it as the reason."),
    dict(id="DIA-06", presentation="acute_diarrhoea", kind="substitute",
         chunk_id="acute_diarrhoea::uganda_clinical_guidelines_2023::p469-471::1",
         doc="Uganda Clinical Guidelines 2023 (4th ed.)", section="6.1.5 Diarrhoea",
         pdf_pages="469-471", printed_pages="403-405",
         quote="Prevent or correct dehydration with ORS or IV fluids according to treatment plans A, B or C",
         note="Plus zinc 20 milligrams per day for children older than six months for 10-14 days."),
    dict(id="DIA-07", presentation="acute_diarrhoea", kind="escalation",
         chunk_id="acute_diarrhoea::uganda_clinical_guidelines_2023::p469-471::1",
         doc="Uganda Clinical Guidelines 2023 (4th ed.)", section="6.1.5 Diarrhoea",
         pdf_pages="469-471", printed_pages="403-405",
         quote="Shock, failure to feed, mental confusion",
         note="UCG red flags in full: fever; extremes of age; travel from a known endemic area; "
              "dysentery; shock, failure to feed, mental confusion."),
    dict(id="DIA-08", presentation="acute_diarrhoea", kind="first_choice",
         chunk_id="acute_diarrhoea::who_aware_book_2022::p185-200::1",
         doc="WHO AWaRe Antibiotic Book (2022)",
         section="14. Acute infectious diarrhoea/gastroenteritis",
         pdf_pages="185-200", printed_pages="169-184",
         quote="ciprofloxacin is the first choice, but azithromycin is preferred in areas with a high prevalence of ciprofloxacin resistance",
         note="Both Watch. The only presentation in this pool whose first choice is not Access, "
              "which is itself worth a Category 1 pair."),
]
